### ISSUE TITLE
Forced to use Chartist 0.9.8 but get [object Object] as label

### ISSUE THREAD

**Issue by daN4cat** [mtgibbs/chartist-plugin-barlabels#3]
Wondering if this plugin works with latest Chartist 0.9.8 as I don't get any label but [object Object] instead.

**Comment by mtgibbs** [comment]
I've not updated my current instance of Chartist to latest.  I'll do that and take a look to see what's wrong in a bit.  EDIT: I'm using 0.9.7 just fine.

Can you please share your code snippet with me?

**Comment by daN4cat** [comment]
I tested with vertical bars a currently working piece of code.
I've added your plugin to the min.js and the following in the existing code:

```
    plugins: [
    <snip>
      Chartist.plugins.ctBarLabels()
    <snip>
    ]
```

You can see the code here: https://github.com/jekkos/opensourcepos/blob/master/application/views/reports/graphs/bar.php

P.S.: I'm one of the authors of that code, and in specific I worked on the charts using chartist.

**Comment by mtgibbs** [comment]
The code you linked doesn't have any reference to this plugin, but I did notice that your data series is a series of objects, not numbers.  The label is just default displaying each data point.

``` javascript
 var barValue = data.value.x === undefined ? data.value.y : data.value.x;
```

I'm not sure about the structure of your call since it isn't present yet as it comes from php before being rendered.  Can you provide the post-php rendered snippet so we can take a look at the data objects?

**Comment by daN4cat** [comment]
Fair enough, but could you at least make sure the plugin is fine with 0.9.8 even at bower installation time?

And no, the pointer is the current code not the one with the plugin. As said I just added the code from the comment in the plugin list and nothing more.

But I will check your suggestion, thanks for the help.

**Comment by mtgibbs** [comment]
I just need to see the object in the series to see why it's trying to print an object instead of the value.  

Also didn't mean to press close on that, was just hastily pressing buttons.

**Comment by daN4cat** [comment]
Ok. I just run on a demo installation and from inspector here the copy&paste:

```
    // Labels and data series
    var data = {
        labels: ["5.00%","10.00%","30.00%","40.00%","70.00%"],
        series: [{
            name: 'Count',
            data: ["116","1","3","1","1"]       }]
    };

    // We are setting a few options for our chart and override the defaults
    var options = {

        // Specify a fixed width for the chart as a string (i.e. '100px' or '50%')
        width: '100%',

        // Specify a fixed height for the chart as a string (i.e. '100px' or '50%')
        height: '100%',

        // Padding of the chart drawing area to the container element and labels as a number or padding object {top: 5, right: 5, bottom: 5, left: 5}
        chartPadding: {
            top: 20,
            bottom: 100
        },

        // X-Axis specific configuration
        axisX: {
            // Lets offset the chart a bit from the labels
            offset: 120,
            position: 'end'
        },

        // Y-Axis specific configuration
        axisY: {
            // Lets offset the chart a bit from the labels
            offset: 60,
            // The label interpolation function enables you to modify the values
            // used for the labels on each axis.
            labelInterpolationFnc: function(value) {
                                    return value;
                            }
        },

        // plugins configuration
        plugins: [
            Chartist.plugins.ctAxisTitle({
                axisX: {
                    axisTitle: 'Discount Percent',
                    axisClass: 'ct-axis-title',
                    offset: {
                        x: -100,
                        y: 100
                    },
                    textAnchor: 'middle'
                },
                axisY: {
                    axisTitle: 'Count',
                    axisClass: 'ct-axis-title',
                    offset: {
                        x: 0,
                        y: 0
                    },
                    textAnchor: 'middle',
                    flipTitle: false
                }
            }),

            Chartist.plugins.ctPointLabels({
                textAnchor: 'middle'
            })
        ]
    };

    var responsiveOptions = [
        ['screen and (min-width: 640px)', {
            height: '80%',
            chartPadding: {
                top: 20,
                bottom: 0
            },
        }] /*,
        ['screen and (min-width: 1024px)', {
            labelOffset: 80,
            chartPadding: 20
        }]*/
    ];

    new Chartist.Bar('#chart1', data, options, responsiveOptions);

```

**Comment by daN4cat** [comment]
And here the picture of the chart:

![image](https://cloud.githubusercontent.com/assets/636048/20280252/a48d9fca-aaa3-11e6-9db9-cb5df79ac587.png)

**Comment by mtgibbs** [comment]
Alright, thanks.  I'll take a look at this.

**Comment by daN4cat** [comment]
Also this is what we have as chartist and plugins (from our bower.json):

```
    "chartist": "^0.9.8",
    "chartist-plugin-axistitle": "^0.1.0",
    "chartist-plugin-pointlabels": "^0.0.4",
    "chartist-plugin-tooltip": "^0.0.13"
```

**Comment by mtgibbs** [comment]
Ah, you know what.  I don't own the name on bower.io registry.  The repository that is installed from bower is:

https://github.com/Remco75/chartist-plugin-barlabels

Mine is hosted in npm if you want to use it.

**Comment by daN4cat** [comment]
OK, so that might be the issue. I downloaded that version using bower not yours.

Maybe you should change the name and upload to bower your version with a different name.
If that's the case I then need to hardcode the path to your github repo in our bower.json to download the correct version.

**Comment by mtgibbs** [comment]
There's not much of a need for bower ever since npm v3.  I'm not going to change names of my projects because someone else has the name in one of the many repos, especially when it is already published in the repository of my choice with the given name.

https://www.npmjs.com/package/chartist-plugin-barlabels

But let me know if my version works for you and if there are any issues!

**Comment by daN4cat** [comment]
Thanks for looking into this and sorry for the mixup.
I'll see what npm v3 migration will imply, but as first step I'll add the URL to bower to download your version.

**Comment by daN4cat** [comment]
Pointed to your version works fine.

Thank you for the support and sorry again for the useless noise, but I hope it will be useful for somebody else in the future in case they repeat my same mistake.

And thank you for the plugin.

**Comment by mtgibbs** [comment]
👍 No problem, glad it works!  Issues and PRs always welcome!

**Comment by daN4cat** [comment]
I just committed to OSPOS the change so your plugin is now part of that Open Source software.
Maybe you are not familiar with that but it's a Point Of Sale solution used in shops for sales and receipt printing with all the stock management and etc.
All free and open source.
Your code license is included in the License file we automatically generate and it's visible from the Config pages.
