### ISSUE TITLE
error [object object]

### ISSUE THREAD

**Issue by chris93111** [mtgibbs/chartist-plugin-barlabels#4]
hello i would like use this plugin for display data of bar but is display "[object object]

 // test

         var datatestsSubscriptionChart = {
          labels: ['TST', 'DEV', 'ASB', 'INT'],
          series: [
            [20, 60, 40, 100]

          ]
        };
        var optionstestsSubscriptionChart = {
        plugins: [
Chartist.plugins.ctBarLabels()

    ],

        axisX: {
                showGrid: false
            },
            low: 0,
            high: 200,
            chartPadding: { top: 0, right: 5, bottom: 0, left: 0}
        };
        var responsiveOptions = [
          ['screen and (max-width: 640px)', {
            seriesBarDistance: 8,
            axisX: {
              labelInterpolationFnc: function (value) {
                return value[0];
              }
            }
          }]
        ];

        var testsSubscriptionChart = Chartist.Bar('#testsSubscriptionChart', datatestsSubscriptionChart, optionstestsSubscriptionChart, responsiveOptions);

![image](https://cloud.githubusercontent.com/assets/27526373/25058934/7cf04b5e-217f-11e7-91e6-5e17b7b47d73.png)

can help me ?

**Comment by mtgibbs** [comment]
Sure, let me recreate your problem real quick. 

But since this happens all the time.  Did you install this plugin from Bower or from NPM?  I am not the owner of the Bower repository of the same name.  The owner of that does not seem to be maintaining their repo the last time this came up.  Take a look at Issue #3 .

**Comment by mtgibbs** [comment]
@chris93111 Any update?

**Comment by chris93111** [comment]
hello mtgibbs 

thanks it's ok , now work correctly ;)
